name: Convert SKEL 4.2.33 to 3.8.99

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download converter
        run: |
          git clone --depth 1 \
            https://github.com/daso132/SpineSkeletonDataConverterXYfix.git \
            converter

      - name: Build converter
        run: |
          cd converter
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j2

      - name: Find SKEL
        run: |
          mkdir -p output

          FILE=$(find input -type f -iname "*.skel" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "ERROR: input 文件夹中没有 .skel"
            exit 1
          fi

          echo "INPUT_FILE=$FILE" >> "$GITHUB_ENV"
          echo "Found: $FILE"

      - name: Convert 4.2.33 to 3.8.99
        run: |
          ./converter/build/SpineSkeletonDataConverter \
            "$INPUT_FILE" \
            "output/CH0335_noweapon_spr_3.8.99.skel" \
            -v 3.8.99 \
            --XYconvert

      - name: Check result
        run: |
          ls -lh output/
          file output/CH0335_noweapon_spr_3.8.99.skel

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: CH0335-3.8.99
          path: output/CH0335_noweapon_spr_3.8.99.skel
